### PR TITLE
Make default QoS Level to AtLeastOnce to match default SDK behavior

### PR DESCRIPTION
**Pull request by kbeaugrand**
## Description
Following the default Azure Device SDK behavior, the default MQTT QoS Level is 1 (AtLeastOnce). This PR is the change i purpose to match this defaults: 

* default constructor argument value to QoS 1
* Add some notes on the README to explain that

## Motivation and Context
I was frustating while starting the SDK on my ESP32 when I didn't received the messages on the hub, I was wondering that the works as the standard Device SDK.

## Screenshots

The Azure Documentation: 
[https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-device-sdks](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-device-sdks)

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.Azure.Devices?pullRequest=74) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.Azure.Devices?pullRequest=74) before we can accept your contribution.<br/><br/>:x: kbeaugrand [sign now](https://cla.dotnetfoundation.org/nanoframework/nanoFramework.Azure.Devices?pullRequest=74)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nanoFramework.Azure.Devices?pullRequest=74) it.</sub>

**Comment by kbeaugrand** [comment]
I checked the Breaking-Change option, but I don't know if you consider it a break since a default option has been changed, which could cause problems even if it doesn't really block.

**Comment by Ellerbach** [comment]
> I checked the Breaking-Change option, but I don't know if you consider it a break since a default option has been changed, which could cause problems even if it doesn't really block.

It's ok. And if it does align properly with the rest of the SDK, then that's ok. The Azure DeviceClient has been preview anyway. So not an issue.

**Review by Ellerbach — APPROVED** [review]
Thanks for the addition and alignement with the other SDK. I guess this will reduce the number of questions as well on this topic :-)

**Comment by kbeaugrand** [comment]
Even if this PR is very small, it is for pleasure that I will add myself to the list of contributors.

**Pull request merged**
